# Generated by Django 5.1.1 on 2024-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIQAMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('message_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('is_thumb_up', models.BooleanField(default=False)),
                ('is_thumb_down', models.BooleanField(default=False)),
                ('reflect_reason', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aiqa_messages',
                'unique_together': {('user_id', 'session_id', 'message_id')},
            },
        ),
    ]
