# Generated by Django 5.1.1 on 2024-10-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRobot', '0002_ipstatistics'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipstatistics',
            table='aiqa_ipStatistics',
        ),
    ]
