# Generated by Django 5.1.1 on 2024-10-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRobot', '0003_alter_ipstatistics_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipstatistics',
            name='api_endpoint',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ipstatistics',
            name='method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
