# Generated by Django 5.1.1 on 2024-11-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRobot', '0004_ipstatistics_api_endpoint_ipstatistics_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiqamessage',
            name='quotes',
            field=models.TextField(null=True),
        ),
    ]
