# Generated by Django 5.1.1 on 2024-11-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRobot', '0005_aiqamessage_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiqamessage',
            name='quote_file',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
