# Generated by Django 5.1.1 on 2024-11-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRobot', '0006_aiqamessage_quote_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiqamessage',
            name='quote_file',
            field=models.TextField(null=True),
        ),
    ]
